# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c0tdKxPEkymWuMG-PIogm2SQemluWXpu
"""

#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""
Executive Risk Dashboard – Streamlit app
---------------------------------------
* Theme (Tiffany blue) and logo are defined directly in this file.
* Data source: demo_nsfw_personal.csv (must be in the repo root).
"""

import pathlib
import pandas as pd
import streamlit as st
from tqdm import tqdm

# -----------------------------------------------------------------
# 0️⃣  Paths & constants
# -----------------------------------------------------------------
ROOT_DIR   = pathlib.Path(__file__).parent
DATA_PATH  = ROOT_DIR / "demo_nsfw_personal.csv"
LOGO_PATH  = ROOT_DIR / "logo.png"

# -----------------------------------------------------------------
# 1️⃣  Page configuration (title, icon, layout)
# -----------------------------------------------------------------
st.set_page_config(
    page_title="Executive Risk Dashboard",
    page_icon="🔍",
    layout="wide",
    initial_sidebar_state="expanded",
)

# -----------------------------------------------------------------
# 2️⃣  Inject Tiffany‑blue CSS (no config.toml needed)
# -----------------------------------------------------------------
CUSTOM_CSS = """
/* Global page styling */
body {
    background-color: #0ABAB5;      /* Tiffany blue */
    color: #ffffff;                /* White text */
}

/* Sidebar, header & footer */
[data-testid="stSidebar"] { background-color: #0ABAB5; }
section[data-testid="stHeader"] { background-color: #0ABAB5; }
footer { background-color: #0ABAB5; }

/* Reduce vertical padding */
.block-container { padding-top: 0rem; padding-bottom: 0rem; }

/* Logo image sizing (used in the sidebar) */
.logo-img { max-height: 60px; margin-right: 12px; }
"""
st.markdown(f"<style>{CUSTOM_CSS}</style>", unsafe_allow_html=True)

# -----------------------------------------------------------------
# 3️⃣  Show the logo in the sidebar
# -----------------------------------------------------------------
if LOGO_PATH.is_file():
    st.sidebar.image(str(LOGO_PATH), width=120)   # adjust width if you like
else:
    st.sidebar.warning("⚠️ logo.png not found – please add it to the repo root.")

# -----------------------------------------------------------------
# 4️⃣  Load the CSV (cached – runs only once per session)
# -----------------------------------------------------------------
@st.cache_data(ttl=86400)   # refresh daily
def load_data() -> pd.DataFrame:
    if not DATA_PATH.is_file():
        st.error(f"❌ Data file not found at `{DATA_PATH}`")
        st.stop()

    # Read CSV – the file you already generated
    df = pd.read_csv(DATA_PATH, engine="python", encoding="utf-8")

    # Convert known boolean columns (helps filters)
    bool_cols = [
        "risk_flag_email", "flag_nsfw", "flag_fin",
        "flag_compliance", "over_limit", "personal_use",
        "flag_compliance_txn"
    ]
    for col in bool_cols:
        if col in df.columns:
            df[col] = df[col].astype(bool)

    # Ensure timestamps are datetime objects (if present)
    if "ts" in df.columns:
        df["ts"] = pd.to_datetime(df["ts"], utc=True, errors="coerce")

    return df.copy()

df = load_data()

# -----------------------------------------------------------------
# 5️⃣  Title & description
# -----------------------------------------------------------------
st.title("🔎 Executive Risk Dashboard")
st.markdown(
    """
    A lightweight demo that joins **customer remarks**, **sentiment analysis**,
    and **synthetic transaction data**, then highlights high‑value, negative‑sentiment cases.
    """
)

# -----------------------------------------------------------------
# 6️⃣  Sidebar filters
# -----------------------------------------------------------------
st.sidebar.header("🔧 Filters")

# 6.1 Executive selector (multi‑select)
exec_options = sorted(df["exec_id"].unique())
selected_execs = st.sidebar.multiselect(
    "👤 Executive(s)",
    options=exec_options,
    default=exec_options[:5],
    help="Select one or more employee IDs."
)

# 6.2 Risk‑flag toggles
show_risky_email = st.sidebar.checkbox(
    "🚩 Show only risky e‑mail rows",
    value=False,
    help="Filters to rows where `risk_flag_email` is True."
)

show_nsfw_chat = st.sidebar.checkbox(
    "🔞 Show only NSFW chat rows",
    value=False,
    help="Filters to rows where `flag_nsfw` is True."
)

# 6.3 Transaction category filter
if "category" in df.columns:
    cat_options = sorted(df["category"].dropna().unique())
    selected_cats = st.sidebar.multiselect(
        "💳 Transaction category",
        options=cat_options,
        default=cat_options,
        help="Filter synthetic credit‑card transactions by category."
    )
else:
    selected_cats = []

# 6.4 Over‑limit toggle
show_over_limit = st.sidebar.checkbox(
    "⚠️ Show only over‑limit transactions",
    value=False,
    help="Filters to rows where `over_limit` is True."
)

# 6.5 Personal‑use toggle
show_personal_use = st.sidebar.checkbox(
    "🧾 Show only personal‑use transactions",
    value=False,
    help="Filters to rows where `personal_use` is True."
)

# -----------------------------------------------------------------
# 7️⃣  Apply filters
# -----------------------------------------------------------------
filtered = df.copy()

if selected_execs:
    filtered = filtered[filtered["exec_id"].isin(selected_execs)]

if show_risky_email:
    filtered = filtered[filtered["risk_flag_email"]]

if show_nsfw_chat:
    filtered = filtered[filtered["flag_nsfw"]]

if selected_cats:
    filtered = filtered[filtered["category"].isin(selected_cats)]

if show_over_limit:
    filtered = filtered[filtered["over_limit"]]

if show_personal_use:
    filtered = filtered[filtered["personal_use"]]

# -----------------------------------------------------------------
# 8️⃣  Main page – metrics & table
# -----------------------------------------------------------------
st.subheader("📊 Overview")
col_a, col_b, col_c = st.columns(3)

with col_a:
    st.metric(
        label="Total Employees",
        value=f"{df['exec_id'].nunique():,}"
    )
with col_b:
    st.metric(
        label="Risky e‑mail execs",
        value=f"{df['risk_flag_email'].sum():,}"
    )
with col_c:
    st.metric(
        label="NSFW chats",
        value=f"{df['flag_nsfw'].sum():,}"
    )

st.markdown("---")

# 8.1 Show the filtered dataframe
st.subheader("🗂️ Filtered data")
display_cols = [
    "exec_id",
    "email_message",
    "email_sentiment",
    "risk_flag_email",
    "message",
    "flag_nsfw",
    "flag_fin",
    "flag_compliance",
    "chat_sentiment",
    "ts",
    "category",
    "amt_usd",
    "over_limit",
    "personal_use",
    "flag_compliance_txn",
]

st.dataframe(
    filtered[display_cols],
    use_container_width=True,
    height=500,
)

# -----------------------------------------------------------------
# 9️⃣  Download button – export filtered view as CSV
# -----------------------------------------------------------------
def convert_df_to_csv(df_: pd.DataFrame) -> bytes:
    """Return CSV bytes for Streamlit download button."""
    return df_.to_csv(index=False).encode("utf-8")

csv_bytes = convert_df_to_csv(filtered[display_cols])

st.download_button(
    label="💾 Download filtered view as CSV",
    data=csv_bytes,
    file_name="filtered_employee_risk.csv",
    mime="text/csv",
    help="Download the rows currently displayed in the table.",
)

# -----------------------------------------------------------------
# 🔚  Footer / disclaimer
# -----------------------------------------------------------------
st.caption(
    "© 2025 Your Company – Internal risk dashboard. "
    "Data is synthetic except for the Enron e‑mail sample."
)